sudo: false

addons:
  apt:
    packages:
    - libsndfile1

cache:
  directories:
  - $HOME/env

language: python

notifications:
  email: false

python:
    - "2.7"
    - "3.4"
    - "3.5"

before_install:
    - bash .travis_dependencies.sh
    - export PATH="$HOME/env/miniconda$TRAVIS_PYTHON_VERSION/bin:$PATH";
    - hash -r
    - source activate test-environment

install:
    - pip install -r requirements.txt

script:
    - python --version
    - python -m pytest

after_success:
    - pip uninstall -y amen

after_failure:
    - pip uninstall -y amen
